import type { Metadata } from "next";
import { Anton, Oswald, Bebas_Neue } from "next/font/google";
import "./globals.css";
import backgroundImage from "@/assets/background.png";
import { Providers } from "./providers";

const anton = Anton({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-anton",
});

const bebas = Bebas_Neue({ 
  subsets: ["latin"], 
  weight: "400",
  variable: "--font-bebas",
});

const oswald = Oswald({
  weight: ["200", "300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-oswald",
});

export const metadata: Metadata = {
  title: "Ring Strike App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${anton.variable} ${bebas.variable} ${oswald.variable} font-sans`}
        style={{
          backgroundImage: `url(${backgroundImage.src})`,
          backgroundSize: "cover",
          backgroundRepeat: "no-repeat",
          backgroundPosition: "center center",
          minHeight: "100vh",
        }}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
